export const homeObjOne = {
    id: 'about', 
    lightBg: true, 
    lightText: false, 
    lightTextDesc: false, 
    topLine: 'Instant Production', 
    headline: 'Konstruct is a internal product development tool for non-engineers', 
    description: 'It allows rapid creation and automation of tasks typically done by junior analysts. It aims to solve fragmented permission granting, complicated IDE set-up, and the difficulty of launching servers',
    buttonLabel: 'Get Started', 
    imgStart: false, 
    img:require('../../images/svg2.svg').default,
    alt: 'Car',
    dark: true, 
    primary: true, 
    darkText: true, 
}

export const homeObjTwo = {
    id: 'Security', 
    lightBg: true, 
    lightText: false, 
    lightTextDesc: false, 
    topLine: 'Secure', 
    headline: 'Due to the internal nature of the tool, security is integral to development', 
    description: 'All data comes in read-only formats, and is secured by encryption and iAM AWS Policies',
    buttonLabel: 'Learn  More', 
    imgStart: true, 
    img:require('../../images/svg3.svg').default,
    alt: 'car2',
    dark: false, 
    primary: false, 
    darkText: true, 
}


export const homeObjThree = {
    id: 'signup', 
    lightBg: false, 
    lightText: true, 
    lightTextDesc: false, 
    topLine: 'Remote Friendly', 
    headline: 'Login Anywhere', 
    description: 'We have you covered.',
    buttonLabel: 'Get Started', 
    imgStart: false, 
    img:require('../../images/svg1.svg').default,
    alt: 'Car',
    dark: true, 
    primary: true, 
    darkText: false, 
}